name: test
run-name: ${{ github.actor }} is running Foundry tests
on: [push]
jobs:
  solidity-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: write # To push a branch
      pull-requests: write # To create a PR from that branch
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build Book
        run: nix develop -c forge doc --build
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: "docs/book"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
