name: test
run-name: ${{ github.actor }} is running Foundry tests
on: [push]
jobs:
  solidity-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Foundry test
        run: nix develop -c forge test --no-auto-detect
